### ISSUE TITLE
News Block auf der Startseite kaputt

### ISSUE THREAD

**Issue by marschwar** [marschwar/fpe-homepage#30]
Irgendwie ist der News Block bei den Umbauten kaputt gegangen.

![gnome-shell-screenshot-u4y7cz](https://user-images.githubusercontent.com/4807823/35170218-b3580292-fd5f-11e7-8a72-85388b4972a4.png)

**Comment by inevs** [comment]
Design der einfachen Seite zurückgebaut, das hat den News-Bereich kaputt gemaxcht
