### ISSUE TITLE
Installscript

### ISSUE THREAD

**Issue by inevs** [marschwar/fpe-homepage#34]
Strip all the needed content from the folder to upload into prod

**Comment by marschwar** [comment]
https://linux.die.net/man/1/sitecopy

**Comment by marschwar** [comment]
Das Theme kann schon kopiert werden. Fehlt noch ein ```drush config-export``` und dann der sync des config Verzeichnis

**Comment by marschwar** [comment]
@inevs Bitte noch einmal eine neue Version von sitecopyrc erstellen und `install.sh` aufrufen. 
Danach kannst du mit `./update-production.sh` sowohl das theme als auch die config kopieren. Die config muss dann noch einmal manuell übernommen werden. Sicher ist sicher!
