### ISSUE TITLE
News zeigt die Headline überlagert weil Bild fehlt

### ISSUE THREAD

**Issue by inevs** [marschwar/fpe-homepage#38]
![screen shot 2018-02-05 at 19 23 36](https://user-images.githubusercontent.com/244863/35821673-1627e69c-0aaa-11e8-9cee-710b01e2e36b.png)

**Comment by marschwar** [comment]
Offenbar fehlte ein Haken bei "Feldvorlage verwenden". Warum sich das lokal anders verhält, verstehe ich nicht.
![gnome-shell-screenshot-am7ydz](https://user-images.githubusercontent.com/4807823/36017828-a391a9ec-0d79-11e8-8f74-a191234d137f.png)

**Comment by inevs** [comment]
Ah ok, ich kann da ja mal schauen, ob ich was dazu finde.
Cool dass du es gefunden hast
