### ISSUE TITLE
EMTV-Logo einbauen

### ISSUE THREAD

**Issue by inevs** [marschwar/fpe-homepage#61]
Hey ihr, könnt ihr eines dieser Logos benutzen um es ganz unten auf die Seite neben dem Impressum zu platzieren?

soll das Icon dann weiß hinterlegt werden? Das ist ja jetzt Blau und Blau auf Blau sieht man nicht :-)
Was heißt neben dem Impressum? Links davon oder zwischen Impressum-Link und Kontakt? Auf dem Mobiltelefon haben wir gar nicht so viel Platz, wo soll es dann stehen?

Kann das Logo vielleicht um die Schrift und Emblem einen weißen Rand bekommen, ich finde das sieht so doof aus, wenn das so ein komplettes weißes Rechteck um das Logo ist. 

Neben Kontakt rechts sieht das glaube ich gut aus. Und bei der mobilen Ansicht, würde das über die gelben Icons passen?

**Comment by inevs** [comment]
![emtv_cs3](https://user-images.githubusercontent.com/244863/36355433-6b12ee2a-14e3-11e8-8cb0-dab01daad475.png)

**Comment by inevs** [comment]
Modifiziertes Logo mit weißem Rand um Kreis und Schriftzug
![emtv](https://user-images.githubusercontent.com/244863/36355869-38aad66c-14ea-11e8-8ab5-d045ad2d50fb.png)

**Comment by inevs** [comment]
Modifiziertes Logo mit weißem Rand um Kreis und Schriftzug 800x333px
![emtv_800](https://user-images.githubusercontent.com/244863/36355880-5dd22300-14ea-11e8-9274-314b8e790f40.png)

**Comment by marschwar** [comment]
Ich habe das Logo auch als svg

**Comment by marschwar** [comment]
https://github.com/marschwar/fpe-homepage/blob/master/themes/fpe/images/optimized/emtv.svg
